# Generated by Django 5.1.7 on 2025-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
