# Generated by Django 5.2.2 on 2025-06-09 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0002_verification_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
