services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: waypoint_db
      POSTGRES_USER: waypoint_user
      POSTGRES_PASSWORD: waypoint_password_2024

  web:
    build: .
    volumes:
      - .:/home/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: 'django-insecure-4$$96vkmn3@flse_=1zec=ma=o&j0en_c0rutj7*$$1r)$$59b)t'
      ALLOWED_HOSTS: '*'
      DB_NAME: waypoint_db
      DB_USER: waypoint_user
      DB_PASSWORD: waypoint_password_2024
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
