import { StyleSheet, Dimensions, Platform } from "react-native";
import { useTheme } from "@context/ThemeContext";

const DRAWER_WIDTH = 300;

export default function useStyles() {
  const { theme } = useTheme();

  return StyleSheet.create({
    container: {
      flex: 1,
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    map: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    markerContainer: {
      backgroundColor: 'white',
      borderRadius: 15,
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#000',
    },
    markerContainerDelivered: {
      borderColor: '#4CAF50',
      backgroundColor: '#E8F5E9',
    },
    markerText: {
      color: '#000',
      fontSize: 16,
      fontWeight: 'bold',
    },
    currentPositionContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    navigationIcon: {
      backfaceVisibility: 'hidden',
      position: 'absolute',
    },
    menuButton: {
      position: 'absolute',
      top: 16,
      right: 16,
      backgroundColor: '#000',
      borderRadius: 8,
      padding: 12,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    logoutButton: {
      position: 'absolute',
      top: 40,
      left: 20,
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    recenterButton: {
      position: 'absolute',
      bottom: 16,
      right: 16,
      backgroundColor: '#000',
      borderRadius: 8,
      padding: 12,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    drawerContainer: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    drawerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E0E0E0',
    },
    drawerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#000',
    },
    closeButton: {
      padding: 8,
    },
    drawerContent: {
      flex: 1,
      padding: 16,
    },
    packageList: {
      flex: 1,
    },
    packageListContent: {
      padding: 20,
    },
    packageItem: {
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    packageItemDelivered: {
      borderColor: '#4CAF50',
      backgroundColor: '#F1F8E9',
    },
    packageHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    packageNumber: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
    },
    packageAddress: {
      fontSize: 14,
      color: '#666',
      marginBottom: 4,
    },
    packageRecipient: {
      fontSize: 14,
      color: '#666',
      marginBottom: 4,
    },
    packagePhone: {
      fontSize: 14,
      color: '#666',
    },
    indexBadge: {
      width: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    indexText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    recipientName: {
      fontSize: 16,
      fontWeight: 'bold',
    },
    address: {
      fontSize: 14,
      color: '#666',
      flex: 1,
      marginRight: 10,
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    callButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
    },
    completeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
    },
    completeButtonText: {
      fontSize: 14,
      fontWeight: '600',
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyStateTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 16,
      marginBottom: 8,
    },
    emptyStateSubtitle: {
      fontSize: 16,
      textAlign: 'center',
      paddingHorizontal: 32,
    },
    centerContent: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    errorText: {
      fontSize: 16,
      textAlign: 'center',
      marginHorizontal: 20,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyText: {
      fontSize: 16,
      color: '#666',
    },
  });
} 