import { StyleSheet, Dimensions } from "react-native";
import { useTheme } from "@context/ThemeContext";

export default function useStyles() {
  const { theme } = useTheme();

  return StyleSheet.create({
    container: {
      flex: 1,
    },
    map: {
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').height,
    },
    markerContainer: {
      backgroundColor: 'white',
      borderRadius: 15,
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#000',
    },
    markerContainerDelivered: {
      borderColor: '#4CAF50',
      backgroundColor: '#E8F5E9',
    },
    markerText: {
      color: '#000',
      fontSize: 16,
      fontWeight: 'bold',
    },
    currentPositionContainer: {
      width: 35,
      height: 35,
      backgroundColor: 'transparent',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    navigationIcon: {
      backfaceVisibility: 'hidden',
      position: 'absolute',
    },
    menuButton: {
      position: 'absolute',
      top: 40,
      right: 20,
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    drawerContainer: {
      flex: 1,
    },
    drawerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1.41,
    },
    drawerTitle: {
      fontSize: 24,
      fontWeight: 'bold',
    },
    closeButton: {
      padding: 8,
    },
    packageList: {
      flex: 1,
    },
    packageListContent: {
      padding: 20,
    },
    packageItem: {
      padding: 15,
      borderRadius: 10,
      backgroundColor: '#f5f5f5',
      marginBottom: 10,
    },
    packageHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    indexBadge: {
      width: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
    },
    indexText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    recipientName: {
      fontSize: 16,
      fontWeight: 'bold',
    },
    address: {
      fontSize: 14,
      color: '#666',
      flex: 1,
      marginRight: 10,
    },
    addressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    callButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
    },
    completeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
    },
    completeButtonText: {
      fontSize: 14,
      fontWeight: '600',
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyStateTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginTop: 16,
      marginBottom: 8,
    },
    emptyStateSubtitle: {
      fontSize: 16,
      textAlign: 'center',
      paddingHorizontal: 32,
    },
    recenterButton: {
      position: 'absolute',
      bottom: 40,
      right: 20,
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    centerContent: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    errorText: {
      fontSize: 16,
      textAlign: 'center',
      marginHorizontal: 20,
    },
    logoutButton: {
      position: 'absolute',
      top: 40,
      left: 20,
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
  });
} 