# Generated by Django 5.1.7 on 2025-03-20 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for geolocation', max_digits=9, null=True)),
                ('recipient', models.CharField(max_length=50)),
                ('recipientPhoneNumber', models.CharField(max_length=10)),
                ('deliveryDate', models.DateField()),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for geolocation', max_digits=9, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Package weight (e.g., in kilograms)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=15, unique=True)),
                ('kilogramCapacity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageSequence', models.JSONField(default=list, help_text='Ordered list of Package IDs representing delivery sequence')),
                ('mapRoute', models.JSONField(default=list, help_text='A map drawing of the route')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
