# Generated by Django 5.1.7 on 2025-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeassignment',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
