# Generated by Django 5.1.7 on 2025-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageID',
            field=models.CharField(default='7aabbc4a2efe78cf68d5c3d2', editable=False, max_length=24, unique=True),
        ),
    ]
