# Generated by Django 5.1.7 on 2025-03-21 05:51

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_package_packageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageID',
            field=models.CharField(default=delivery.models.generate_package_id, editable=False, max_length=12, unique=True),
        ),
    ]
