# Generated by Django 5.2.17 on 2026-09-24 12:51

import django.db.models.deletion
from django.db import migrations, models


def assign_single_company(apps, schema_editor):
    """Attach existing packages/trucks to the company when there is exactly one.

    With several companies there is no safe way to guess ownership, so rows stay
    unassigned (and invisible to managers) until fixed by hand.
    """
    Company = apps.get_model('authentication', 'Company')
    Package = apps.get_model('delivery', 'Package')
    Truck = apps.get_model('delivery', 'Truck')
    companies = list(Company.objects.all()[:2])
    if len(companies) != 1:
        return
    company = companies[0]
    Package.objects.filter(company__isnull=True).update(company=company)
    Truck.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_and_user_company_verified'),
        ('delivery', '0010_alter_package_recipientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this truck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='authentication.company'),
        ),
        migrations.RunPython(assign_single_company, migrations.RunPython.noop),
    ]
