# Generated by Django 5.2.17 on 2026-09-24 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_package_truck_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='routeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('isActive', True)), fields=('driver',), name='one_active_route_per_driver'),
        ),
    ]
