# Generated by Django 5.2.17 on 2026-09-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_one_active_route_per_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading', models.FloatField(blank=True, help_text='Degrees clockwise from north, [0, 360)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Metres per second', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Horizontal accuracy in metres', null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True, help_text='Server time of the last update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
