# Generated by Django 5.2.17 on 2026-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_truckerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='recipientEmail',
            field=models.EmailField(blank=True, help_text='Email address of the package recipient for notifications; none means no email is sent', max_length=254, null=True),
        ),
    ]
